export const artists = [
    { name: "Miles Davis", country: "US" },
    { name: "Adele", country: "UK" },
    { name: "Beyoncé", country: "US" },
    { name: "Tame Impala", country: "AU" },
    { name: "Shakira", country: "CO" },
    { name: "Drake", country: "CA" },
    { name: "Sia", country: "AU" },
    { name: "Coldplay", country: "UK" },
    { name: "Ed Sheeran", country: "UK" },
    { name: "Bad Bunny", country: "PR" },
    { name: "Dua Lipa", country: "UK" },
    { name: "The Weeknd", country: "CA" },
    { name: "Luis Fonsi", country: "PR" },
    { name: "J Balvin", country: "CO" },
    { name: "Rihanna", country: "Barbados" },
    { name: "Kendrick Lamar", country: "US" },
    { name: "Billie Eilish", country: "US" },
    { name: "Harry Styles", country: "UK" },
    { name: "Ariana Grande", country: "US" },
    { name: "Post Malone", country: "US" },
    { name: "Bruno Mars", country: "US" },
    { name: "Maroon 5", country: "US" },
    { name: "Katy Perry", country: "US" },
    { name: "Tina Turner", country: "US" },
    { name: "P!nk", country: "US" },
    { name: "Taylor Swift", country: "US" },
    { name: "Justin Bieber", country: "CA" },
    { name: "Sam Smith", country: "UK" },
    { name: "Lady Gaga", country: "US" },
    { name: "Lil Nas X", country: "US" },
    { name: "Imagine Dragons", country: "US" },
    { name: "Miley Cyrus", country: "US" },
    { name: "Nicky Jam", country: "PR" },
    { name: "Shawn Mendes", country: "CA" },
    { name: "Celine Dion", country: "CA" },
    { name: "Carly Rae Jepsen", country: "CA" },
    { name: "Post Malone", country: "US" },
    { name: "Kacey Musgraves", country: "US" },
    { name: "The Chainsmokers", country: "US" },
    { name: "Florence + The Machine", country: "UK" },
    { name: "Paramore", country: "US" },
    { name: "Green Day", country: "US" },
    { name: "Linkin Park", country: "US" },
    { name: "Foo Fighters", country: "US" },
    { name: "Fall Out Boy", country: "US" },
    { name: "Twenty One Pilots", country: "US" },
    { name: "The Killers", country: "US" },
    { name: "BTS", country: "KR" },
    { name: "Blackpink", country: "KR" },
    { name: "EXO", country: "KR" },
    { name: "Big Bang", country: "KR" },
    { name: "Twice", country: "KR" },
    { name: "G-Dragon", country: "KR" },
    { name: "Lorde", country: "NZ" },
    { name: "Robbie Williams", country: "UK" },
    { name: "Snoop Dogg", country: "US" },
    { name: "Eminem", country: "US" },
    { name: "Nicki Minaj", country: "US" },
    { name: "Travis Scott", country: "US" },
    { name: "Lil Wayne", country: "US" },
    { name: "Jay-Z", country: "US" },
    { name: "R. Kelly", country: "US" },
    { name: "Usher", country: "US" },
    { name: "Marvin Gaye", country: "US" },
    { name: "Stevie Wonder", country: "US" },
    { name: "Alicia Keys", country: "US" },
    { name: "Norah Jones", country: "US" },
    { name: "Sade", country: "UK" },
    { name: "Alanis Morissette", country: "CA" },
    { name: "The Tragically Hip", country: "CA" },
    { name: "Arcade Fire", country: "CA" },
    { name: "The Weeknd", country: "CA" },
    { name: "Gwen Stefani", country: "US" },
    { name: "No Doubt", country: "US" },
    { name: "Beck", country: "US" },
    { name: "Kings of Leon", country: "US" },
    { name: "Alicia Keys", country: "US" },
    { name: "Bruno Mars", country: "US" },
    { name: "John Legend", country: "US" },
    { name: "Sia", country: "AU" },
    { name: "Kylie Minogue", country: "AU" },
    { name: "Silverchair", country: "AU" },
    { name: "Crowded House", country: "NZ" },
    { name: "The Mamas & The Papas", country: "US" },
    { name: "Simon & Garfunkel", country: "US" },
    { name: "The Beach Boys", country: "US" },
    { name: "Billy Joel", country: "US" },
    { name: "Elton John", country: "UK" },
    { name: "David Bowie", country: "UK" },
    { name: "Queen", country: "UK" },
    { name: "The Rolling Stones", country: "UK" },
    { name: "The Who", country: "UK" },
    { name: "Led Zeppelin", country: "UK" },
    { name: "AC/DC", country: "AU" },
    { name: "Metallica", country: "US" },
    { name: "Guns N' Roses", country: "US" },
    { name: "Linkin Park", country: "US" },
    { name: "Radiohead", country: "UK" },
    { name: "Oasis", country: "UK" },
    { name: "Blur", country: "UK" },
    { name: "Pulp", country: "UK" },
    { name: "The Cure", country: "UK" },
    { name: "Roxy Music", country: "UK" },
    { name: "Depeche Mode", country: "UK" },
    { name: "The Smiths", country: "UK" },
    { name: "Joy Division", country: "UK" },
    { name: "The Clash", country: "UK" },
    { name: "The Sex Pistols", country: "UK" },
    { name: "Talking Heads", country: "US" },
    { name: "Fiona Apple", country: "US" },
    { name: "Liz Phair", country: "US" },
    { name: "Paramore", country: "US" },
    { name: "The Fray", country: "US" },
    { name: "Panic! At The Disco", country: "US" },
    { name: "Fall Out Boy", country: "US" },
    { name: "Weezer", country: "US" },
    { name: "My Chemical Romance", country: "US" },
    { name: "Yellowcard", country: "US" },
    { name: "Dashboard Confessional", country: "US" },
    { name: "The All-American Rejects", country: "US" },
    { name: "The Killers", country: "US" },
    { name: "Imagine Dragons", country: "US" },
    { name: "Paramore", country: "US" },
    { name: "Bully", country: "US" },
    { name: "Death Cab for Cutie", country: "US" },
    { name: "Bright Eyes", country: "US" },
    { name: "The Postal Service", country: "US" },
    { name: "Foster the People", country: "US" },
    { name: "The Lumineers", country: "US" },
    { name: "Of Monsters and Men", country: "IS" },
    { name: "Hozier", country: "IE" },
    { name: "Snow Patrol", country: "UK" },
    { name: "The Script", country: "IE" },
    { name: "The Cranberries", country: "IE" },
    { name: "Enya", country: "IE" },
    { name: "Clannad", country: "IE" },
    { name: "Sinéad O'Connor", country: "IE" },
    { name: "Shane Filan", country: "IE" },
    { name: "Niall Horan", country: "IE" },
    { name: "Lisa Hannigan", country: "IE" },
    { name: "Sinead O'Connor", country: "IE" },
    { name: "Damien Rice", country: "IE" },
    { name: "Imelda May", country: "IE" },
    { name: "Niamh Kavanagh", country: "IE" },
    { name: "Westlife", country: "IE" },
    { name: "Boyzone", country: "IE" },
    { name: "The Corrs", country: "IE" },
    { name: "The 1975", country: "UK" },
    { name: "Bastille", country: "UK" },
    { name: "Mumford & Sons", country: "UK" },
    { name: "James Bay", country: "UK" },
    { name: "George Ezra", country: "UK" },
    { name: "Rag'n'Bone Man", country: "UK" },
    { name: "Tom Odell", country: "UK" },
    { name: "Sam Fender", country: "UK" },
    { name: "Ed Sheeran", country: "UK" },
    { name: "Liam Gallagher", country: "UK" },
    { name: "Dizzee Rascal", country: "UK" },
    { name: "Stormzy", country: "UK" },
    { name: "Jorja Smith", country: "UK" },
    { name: "Raye", country: "UK" },
    { name: "Skepta", country: "UK" },
    { name: "Disclosure", country: "UK" },
    { name: "Chase & Status", country: "UK" },
    { name: "Rudimental", country: "UK" },
    { name: "Clean Bandit", country: "UK" },
    { name: "Jess Glynne", country: "UK" },
    { name: "Anne-Marie", country: "UK" },
    { name: "Dua Lipa", country: "UK" },
    { name: "Lil Simz", country: "UK" },
    { name: "M Huncho", country: "UK" },
    { name: "Headie One", country: "UK" },
    { name: "Digga D", country: "UK" },
    { name: "AJ Tracey", country: "UK" },
    { name: "Loyle Carner", country: "UK" },
    { name: "Stefflon Don", country: "UK" },
    { name: "Stormzy", country: "UK" },
    { name: "J Hus", country: "UK" },
    { name: "Skepta", country: "UK" },
    { name: "Tion Wayne", country: "UK" },
    { name: "D Block Europe", country: "UK" },
    { name: "Nines", country: "UK" },
    { name: "KSI", country: "UK" },
    { name: "Bakar", country: "UK" },
    { name: "Yxng Bane", country: "UK" },
    { name: "Swae Lee", country: "US" },
    { name: "J. Cole", country: "US" },
    { name: "Drake", country: "CA" },
    { name: "Migos", country: "US" },
    { name: "Lil Uzi Vert", country: "US" },
    { name: "21 Savage", country: "UK" },
    { name: "Juice WRLD", country: "US" },
    { name: "XXXTentacion", country: "US" },
    { name: "Lil Pump", country: "US" },
    { name: "Famous Dex", country: "US" },
    { name: "Rico Nasty", country: "US" },
    { name: "K Michelle", country: "US" },
    { name: "Tinashe", country: "US" },
    { name: "Keri Hilson", country: "US" },
    { name: "Kash Doll", country: "US" },
    { name: "Teyana Taylor", country: "US" },
    { name: "Janelle Monáe", country: "US" },
    { name: "H.E.R.", country: "US" },
    { name: "Anderson .Paak", country: "US" },
    { name: "Denzel Curry", country: "US" },
    { name: "Mac Miller", country: "US" },
    { name: "Tyler, The Creator", country: "US" },
    { name: "Travis Scott", country: "US" },
    { name: "SZA", country: "US" },
    { name: "Bhad Bhabie", country: "US" },
    { name: "Lil Tecca", country: "US" },
    { name: "YBN Nahmir", country: "US" },
    { name: "DaBaby", country: "US" },
    { name: "Roddy Ricch", country: "US" },
    { name: "Polo G", country: "US" },
    { name: "Lil Durk", country: "US" },
    { name: "Blxst", country: "US" },
    { name: "Kenny Chesney", country: "US" },
    { name: "Carrie Underwood", country: "US" },
    { name: "Chris Stapleton", country: "US" },
    { name: "Luke Bryan", country: "US" },
    { name: "Brad Paisley", country: "US" },
    { name: "Miranda Lambert", country: "US" },
    { name: "Kacey Musgraves", country: "US" },
    { name: "Zac Brown Band", country: "US" },
    { name: "Jason Aldean", country: "US" },
    { name: "Rascal Flatts", country: "US" },
    { name: "Keith Urban", country: "AU" },
    { name: "Shania Twain", country: "CA" },
    { name: "Tim McGraw", country: "US" },
    { name: "Darius Rucker", country: "US" },
    { name: "Thomas Rhett", country: "US" },
    { name: "Chris Janson", country: "US" },
    { name: "Jordan Davis", country: "US" },
    { name: "Kane Brown", country: "US" },
    { name: "Maren Morris", country: "US" },
    { name: "Brett Young", country: "US" },
    { name: "Russell Dickerson", country: "US" },
    { name: "Mitchell Tenpenny", country: "US" },
    { name: "Ashley McBryde", country: "US" },
    { name: "Laine Hardy", country: "US" },
    { name: "Morgan Wallen", country: "US" },
    { name: "Gabby Barrett", country: "US" },
    { name: "Carly Pearce", country: "US" },
    { name: "Chase Rice", country: "US" },
    { name: "Lindsay Ell", country: "CA" },
    { name: "Jon Pardi", country: "US" },
    { name: "Hunter Hayes", country: "US" },
    { name: "Kelsea Ballerini", country: "US" },
    { name: "Kacey Musgraves", country: "US" },
    { name: "RaeLynn", country: "US" },
    { name: "Jimmie Allen", country: "US" },
    { name: "FGL", country: "US" },
    { name: "Kip Moore", country: "US" },
    { name: "Old Dominion", country: "US" },
    { name: "Jake Owen", country: "US" },
    { name: "Chris Lane", country: "US" },
    { name: "Tyler Farr", country: "US" },
    { name: "Eric Church", country: "US" },
    { name: "Brad Paisley", country: "US" },
    { name: "Blake Shelton", country: "US" },
    { name: "Gary Allan", country: "US" },
    { name: "Trisha Yearwood", country: "US" },
    { name: "Toby Keith", country: "US" },
    { name: "Alan Jackson", country: "US" },
    { name: "Brooks & Dunn", country: "US" },
    { name: "Billy Currington", country: "US" },
    { name: "Clint Black", country: "US" },
    { name: "Reba McEntire", country: "US" },
    { name: "Lee Ann Womack", country: "US" },
    { name: "Dolly Parton", country: "US" },
    { name: "Loretta Lynn", country: "US" },
    { name: "Tammy Wynette", country: "US" },
    { name: "Merle Haggard", country: "US" },
    { name: "Johnny Cash", country: "US" },
    { name: "Willie Nelson", country: "US" },
    { name: "Waylon Jennings", country: "US" },
    { name: "George Jones", country: "US" },
    { name: "Hank Williams", country: "US" },
    { name: "Garth Brooks", country: "US" },
    { name: "Alan Jackson", country: "US" },
    { name: "George Strait", country: "US" },
    { name: "Tim McGraw", country: "US" },
    { name: "Darius Rucker", country: "US" },
    { name: "Kenny Chesney", country: "US" },
    { name: "Luke Bryan", country: "US" },
    { name: "Chris Stapleton", country: "US" },
    { name: "Maren Morris", country: "US" },
    { name: "Kelsea Ballerini", country: "US" },
    { name: "Carly Pearce", country: "US" },
    { name: "Ashley McBryde", country: "US" },
    { name: "Michael Ray", country: "US" },
    { name: "Jordan Davis", country: "US" },
    { name: "Laine Hardy", country: "US" },
    { name: "Tyler Rich", country: "US" },
    { name: "Mickey Guyton", country: "US" },
    { name: "Tenille Townes", country: "CA" },
    { name: "Jade Bird", country: "UK" },
    { name: "Maggie Rogers", country: "US" },
    { name: "Brandi Carlile", country: "US" },
    { name: "Sara Bareilles", country: "US" },
    { name: "Halsey", country: "US" },
    { name: "Demi Lovato", country: "US" },
    { name: "Shawn Mendes", country: "CA" },
    { name: "Niall Horan", country: "IE" },
    { name: "Charli XCX", country: "UK" },
    { name: "Grimes", country: "CA" },
    { name: "Mitski", country: "US" },
    { name: "Phoebe Bridgers", country: "US" },
    { name: "Clairo", country: "US" },
    { name: "Tove Lo", country: "SE" },
    { name: "Ellie Goulding", country: "UK" },
    { name: "Jessie Ware", country: "UK" },
    { name: "Rina Sawayama", country: "JP" },
    { name: "Sophie Ellis-Bextor", country: "UK" },
    { name: "Paloma Faith", country: "UK" },
    { name: "Dido", country: "UK" },
    { name: "Lana Del Rey", country: "US" },
    { name: "SZA", country: "US" },
    { name: "Billie Eilish", country: "US" },
    { name: "Hozier", country: "IE" },
    { name: "Sam Smith", country: "UK" },
    { name: "Ed Sheeran", country: "UK" },
    { name: "Niall Horan", country: "IE" },
    { name: "Shawn Mendes", country: "CA" },
    { name: "Lorde", country: "NZ" },
    { name: "Kacey Musgraves", country: "US" },
    { name: "Carrie Underwood", country: "US" },
    { name: "Lady A", country: "US" },
    { name: "Chris Young", country: "US" },
    { name: "Rascal Flatts", country: "US" },
    { name: "The Band Perry", country: "US" },
    { name: "Old Dominion", country: "US" },
    { name: "Jake Owen", country: "US" },
    { name: "Jimmie Allen", country: "US" },
    { name: "Mickey Guyton", country: "US" },
    { name: "Tenille Townes", country: "CA" },
    { name: "Kelsea Ballerini", country: "US" },
    { name: "Brett Young", country: "US" },
    { name: "Michael Ray", country: "US" },
    { name: "Jordan Davis", country: "US" },
    { name: "Laine Hardy", country: "US" },
    { name: "Tyler Rich", country: "US" },
    { name: "Gabby Barrett", country: "US" },
    { name: "Lindsay Ell", country: "CA" },
    { name: "Chris Lane", country: "US" },
    { name: "Kip Moore", country: "US" },
    { name: "Brad Paisley", country: "US" },
    { name: "Blake Shelton", country: "US" },
    { name: "Reba McEntire", country: "US" },
    { name: "Miranda Lambert", country: "US" },
    { name: "Kacey Musgraves", country: "US" },
    { name: "Jason Aldean", country: "US" },
    { name: "Zac Brown Band", country: "US" },
    { name: "Tim McGraw", country: "US" },
    { name: "Carrie Underwood", country: "US" },
    { name: "Darius Rucker", country: "US" },
    { name: "Chris Stapleton", country: "US" },
    { name: "Luke Bryan", country: "US" },
    { name: "Morgan Wallen", country: "US" },
    { name: "Kacey Musgraves", country: "US" },
    { name: "Kelsea Ballerini", country: "US" },
    { name: "Zac Brown Band", country: "US" },
    { name: "Brett Young", country: "US" },
    { name: "Chris Young", country: "US" },
    { name: "Old Dominion", country: "US" },
    { name: "Jake Owen", country: "US" },
    { name: "Darius Rucker", country: "US" },
    { name: "Eric Church", country: "US" },
    { name: "Garth Brooks", country: "US" },
    { name: "Travis Tritt", country: "US" },
    { name: "Toby Keith", country: "US" },
    { name: "Rascal Flatts", country: "US" },
    { name: "Blake Shelton", country: "US" },
    { name: "Kenny Chesney", country: "US" },
    { name: "Tim McGraw", country: "US" },
    { name: "George Strait", country: "US" },
    { name: "Alan Jackson", country: "US" },
    { name: "Brooks & Dunn", country: "US" },
    { name: "Reba McEntire", country: "US" },
    { name: "Miranda Lambert", country: "US" },
    { name: "Carrie Underwood", country: "US" },
    { name: "Chris Stapleton", country: "US" },
    { name: "Keith Urban", country: "AU" },
    { name: "Garth Brooks", country: "US" },
    { name: "Brad Paisley", country: "US" },
    { name: "Tim McGraw", country: "US" },
    { name: "Luke Bryan", country: "US" },
    { name: "Kenny Chesney", country: "US" },
    { name: "Chris Young", country: "US" },
    { name: "Brett Young", country: "US" },
    { name: "Morgan Wallen", country: "US" },
    { name: "Laine Hardy", country: "US" },
    { name: "Kelsea Ballerini", country: "US" },
    { name: "Gabby Barrett", country: "US" },
    { name: "Mickey Guyton", country: "US" },
    { name: "Lindsay Ell", country: "CA" },
    { name: "Tenille Townes", country: "CA" },
    { name: "Maren Morris", country: "US" },
    { name: "Kacey Musgraves", country: "US" },
    { name: "Carrie Underwood", country: "US" },
    { name: "Zac Brown Band", country: "US" },
    { name: "Rascal Flatts", country: "US" },
    { name: "Lady A", country: "US" },
    { name: "Jimmie Allen", country: "US" },
    { name: "Michael Ray", country: "US" },
    { name: "Jason Aldean", country: "US" },
    { name: "Tim McGraw", country: "US" },
    { name: "Blake Shelton", country: "US" },
    { name: "Reba McEntire", country: "US" },
    { name: "Chris Stapleton", country: "US" },
    { name: "Kacey Musgraves", country: "US" },
    { name: "Miranda Lambert", country: "US" },
    { name: "Trisha Yearwood", country: "US" },
    { name: "Darius Rucker", country: "US" },
    { name: "Lindsay Ell", country: "CA" },
    { name: "Tenille Townes", country: "CA" },
    { name: "Brett Young", country: "US" },
    { name: "Kelsea Ballerini", country: "US" },
    { name: "Old Dominion", country: "US" },
    { name: "Jake Owen", country: "US" },
    { name: "Kenny Chesney", country: "US" },
    { name: "Tim McGraw", country: "US" },
    { name: "Brad Paisley", country: "US" },
    { name: "Blake Shelton", country: "US" },
    { name: "Garth Brooks", country: "US" },
    { name: "Eric Church", country: "US" },
    { name: "Travis Tritt", country: "US" },
    { name: "Keith Urban", country: "AU" },
    { name: "Kacey Musgraves", country: "US" },
    { name: "Carrie Underwood", country: "US" },
    { name: "Reba McEntire", country: "US" },
    { name: "Tim McGraw", country: "US" },
    { name: "Jason Aldean", country: "US" },
    { name: "Lady A", country: "US" },
    { name: "Jordan Davis", country: "US" },
    { name: "Kane Brown", country: "US" },
    { name: "Maren Morris", country: "US" },
    { name: "Gabby Barrett", country: "US" },
    { name: "Rascal Flatts", country: "US" },
    { name: "Blake Shelton", country: "US" },
    { name: "George Strait", country: "US" },
    { name: "Alan Jackson", country: "US" },
    { name: "Darius Rucker", country: "US" },
    { name: "Kenny Chesney", country: "US" },
    { name: "Chris Stapleton", country: "US" },
    { name: "Luke Bryan", country: "US" },
    { name: "Miranda Lambert", country: "US" },
    { name: "Kacey Musgraves", country: "US" },
    { name: "Mickey Guyton", country: "US" },
    { name: "Laine Hardy", country: "US" },
    { name: "Brett Young", country: "US" },
    { name: "Old Dominion", country: "US" },
    { name: "Jason Aldean", country: "US" },
    { name: "Jordan Davis", country: "US" },
    { name: "Michael Ray", country: "US" },
    { name: "Jimmie Allen", country: "US" },
    { name: "Ashley McBryde", country: "US" },
    { name: "Toby Keith", country: "US" },
    { name: "Eric Church", country: "US" },
    { name: "Keith Urban", country: "AU" },
    { name: "Tim McGraw", country: "US" },
    { name: "Blake Shelton", country: "US" },
    { name: "Garth Brooks", country: "US" },
    { name: "Darius Rucker", country: "US" },
    { name: "Carrie Underwood", country: "US" },
    { name: "Chris Stapleton", country: "US" },
    { name: "Zac Brown Band", country: "US" },
    { name: "Mickey Guyton", country: "US" },
    { name: "Kacey Musgraves", country: "US" },
    { name: "Lady A", country: "US" },
    { name: "Morgan Wallen", country: "US" },
    { name: "Kelsea Ballerini", country: "US" },
    { name: "Gabby Barrett", country: "US" },
    { name: "Chris Young", country: "US" },
    { name: "Kane Brown", country: "US" },
    { name: "Darius Rucker", country: "US" },
    { name: "Kenny Chesney", country: "US" },
    { name: "Brad Paisley", country: "US" },
    { name: "Tim McGraw", country: "US" },
    { name: "Zac Brown Band", country: "US" },
    { name: "Laine Hardy", country: "US" },
    { name: "Jordan Davis", country: "US" },
]